### ISSUE TITLE
Add in tests for javascript

### ISSUE THREAD

**Issue by lowks** [censof/ansible-deployment#165]
Add in tests for javascript. Please refer to danial

**Comment by norjuliana** [comment]
Instead of putting test inside Travis,how about just doing it inside docker itself? from what i read,it can be done...
http://becausejavascript.com/faking-x-server-to-run-js-unitintegration-tests-in-chrome/
https://dzone.com/articles/how-to-run-karma-tests-in-a-docker-container

so far already ask him about the test...its already in bitbucket...

**Comment by lowks** [comment]
@norjuliana give it a try :). I am okay so long as when and if it fails it triggers a failure.

**Comment by norjuliana** [comment]
fix #175
